options = optimoptions('ga','PlotFcn', {@gaplotbestf,@gaplotbestindiv},...
                            'PopulationType', 'bitstring',...
                            'CrossoverFcn',@crossover_5_2,...
                            'PopulationSize',100,...
                            'MutationFcn', {@mutationuniform, 0.2},...
                            'MaxGenerations',300,...
                            'Display','iter');

[x,Fval] = ...
    ga(fitnessFunc,35,[],[],[],[],[],[],[],options);